### ISSUE TITLE
Duplicated entry of BULLET_DAMAGE_TO_WORKER in constants.py

### ISSUE THREAD

**Issue by Dmajster** [liagame/python3-bot#1]
BULLET_DAMAGE_TO_WORKER is duplicated in the constants.py 

![image](https://user-images.githubusercontent.com/16271070/52849830-45b25c00-3112-11e9-82cb-3566f4d6bbc8.png)

**Comment by svigelj** [comment]
@Dmajster thanks for reporting! :smiley: 

It is now fixed, so if you download a new bot via Lia cli `bot` command it will have the correct values.
